config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :restaurants do
    resources :reviews, only: %i[new create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :name, :address, :category, presence: true
  validates :category, inclusion: %w[chinese italian japanese french belgian]
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, :rating, presence: true
  validates :rating, numericality: { only_integer: true, in: 0..5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant, only: %i[new create]

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<div class="container">
  <h1>All restaurants</h1>

  <ul>
    <% @restaurants.each do |restaurant| %>
      <li><%= link_to restaurant.name, restaurant_path(restaurant.id) %></li>
    <% end %>
  </ul>

  <%= link_to "Add a new restaurant", new_restaurant_path %>
</div>

app/views/restaurants/new.html.erb
<div class="container">
  <h2>Add your new restaurant</h2>

  <%= form_with model: @restaurant do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :address %>
    <%= f.text_field :address %>
    <%= f.label :phone_number %>
    <%= f.text_field :phone_number %>
    <%= f.label :category %>
    <%= f.text_field :category %>
    <%= f.submit %>
  <% end %>
</div>

app/views/restaurants/show.html.erb
<div class="container">
  <h2><%= @restaurant.name %></h2>
  <p><%= @restaurant.category %></p>
  <p><%= @restaurant.address %></p>
  <p><%= @restaurant.phone_number %></p>

  <p><strong>Reviews</strong></p>
  <ul class="list-group">
    <% @restaurant.reviews.each do |review| %>
      <li class="list-group-item"><%= review.content %></li>
    <% end %>
  </ul>
   <%= link_to "Write a new review",  new_restaurant_review_path(@restaurant) %>
  <br>

  <%= link_to "Back to restaurants", restaurants_path %>
</div>

app/views/reviews/new.html.erb
<div class="container">
  <h1>New review</h1>
  
  <%= simple_form_for [@restaurant, @review] do |f| %>
    <%= f.input :content %>
    <%= f.submit "Submit review", class: "btn btn-primary" %>
  <% end %>
</div>